//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lookeate.Client.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lookeate.Client.Recursos.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search Product....
        /// </summary>
        public static string index_Buscar_producto___ {
            get {
                return ResourceManager.GetString("index.Buscar producto...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Category.
        /// </summary>
        public static string index_Categorias {
            get {
                return ResourceManager.GetString("index.Categorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string index_Iniciar {
            get {
                return ResourceManager.GetString("index.Iniciar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Product.
        /// </summary>
        public static string index_Productos {
            get {
                return ResourceManager.GetString("index.Productos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reserve.
        /// </summary>
        public static string index_Reserva {
            get {
                return ResourceManager.GetString("index.Reserva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Store.
        /// </summary>
        public static string index_Tienda {
            get {
                return ResourceManager.GetString("index.Tienda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All.
        /// </summary>
        public static string index_Todos {
            get {
                return ResourceManager.GetString("index.Todos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a See product.
        /// </summary>
        public static string index_Ver_producto {
            get {
                return ResourceManager.GetString("index.Ver producto", resourceCulture);
            }
        }
    }
}
